/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e9ddff",
        "inverse-primary": "#6d3bd7",
        "surface-container": "#171f33",
        "on-secondary": "#003640",
        "surface-variant": "#2d3449",
        "primary-container": "#a078ff",
        "background": "#020617",
        "error": "#ffb4ab",
        "surface-dim": "#0b1326",
        "surface-tint": "#d0bcff",
        "on-primary-container": "#340080",
        "on-error": "#690005",
        "tertiary": "#4edea3",
        "on-secondary-fixed-variant": "#004e5c",
        "inverse-on-surface": "#283044",
        "surface": "#0b1326",
        "tertiary-fixed-dim": "#4edea3",
        "outline-variant": "#494454",
        "on-tertiary": "#003824",
        "on-tertiary-fixed-variant": "#005236",
        "on-surface": "#dae2fd",
        "surface-container-lowest": "#060e20",
        "on-primary-fixed-variant": "#5516be",
        "outline": "#958ea0",
        "surface-bright": "#31394d",
        "error-container": "#93000a",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-container": "#00a572",
        "on-tertiary-container": "#00311f",
        "inverse-surface": "#dae2fd",
        "secondary": "#4cd7f6",
        "secondary-container": "#03b5d3",
        "on-secondary-container": "#00424e",
        "on-surface-variant": "#cbc3d7",
        "on-primary-fixed": "#23005c",
        "secondary-fixed": "#acedff",
        "on-error-container": "#ffdad6",
        "primary": "#d0bcff",
        "surface-container-low": "#131b2e",
        "on-primary": "#3c0091",
        "primary-fixed-dim": "#d0bcff",
        "on-tertiary-fixed": "#002113",
        "on-background": "#dae2fd",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-container-highest": "#2d3449",
        "surface-container-high": "#222a3d",
        "on-secondary-fixed": "#001f26"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      fontFamily: {
        sans: ["Raleway", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
}

